### ISSUE TITLE
Keys losing their color 

### ISSUE THREAD

**Issue by MikhaD** [MikhaD/wordle#10]
When changing between modes keys return to the correct color for that game correctly. Observed when game was mid way, switched and switched back and previously green keys looked unpressed.

**Comment by big-boots** [comment]
![Screenshot_20220206-125217_Chrome](https://user-images.githubusercontent.com/99105907/152665115-d28c04d7-7111-4f21-b4e3-2ad2f534636c.jpg)

**Comment by big-boots** [comment]
The S should be green
