### ISSUE TITLE
Yesterday’s Word?

### ISSUE THREAD

**Issue by PetuniaPickle** [MikhaD/wordle#11]
Is there a way to find out what yesterdays word was (1.29.22)?

**Comment by MikhaD** [comment]
Yes there is! You can play it again by going to the link for the game number (it won't count towards your stats): https://mikhad.github.io/wordle/#daily/13
If you don't manage to get a word it will tell you the word and its definition on the end screen.

**Comment by PetuniaPickle** [comment]
Thank you! Amazing and it worked!
