### ISSUE TITLE
Double tap causes zoom on some devices

### ISSUE THREAD

**Issue by melloblue** [MikhaD/wordle#18]
There's no need to zoom, but tapping letters close together zooms in unnecessarily.

**Comment by rbrignall** [comment]
This is fixed in my fork (https://github.com/rbrignall/open-byrdle) but it's now too distant from the original to be able to merge.

**Comment by MikhaD** [comment]
@rbrignall How did you fix that? I tried to but wasn't sure how to prevent it on iOS.
@melloblue on what device does this behavior occur?

**Comment by rbrignall** [comment]
@MikhaD I added:
`touch-action: manipulation;'
to the `.row` class in `Keyboard.svelte`.

[Here's the commit](https://github.com/rbrignall/open-byrdle/commit/d2d9942bcb9e4d4692e3b2e2e4b04bca80101144#diff-14b7b0252740affa9492ad32b73d8c1375c53e635ad8b55c751895919f40e7a0) where I made the change.

**Comment by MikhaD** [comment]
Thank you. I have added `touch-action: manipulation;` to the `*` selector in the global style sheet, hopefully that fixes it everywhere. I'll push the changes in the next few hours.

**Comment by lukeswitz** [comment]
Reloading the page, keyboard in focus but board isn’t able to be pinched back into the frame. Need a css constraint like the one for fixing the keyboard as mentioned above 

‘touch-action: none;’ fixes this easily

**Comment by melloblue** [comment]
> @rbrignall How did you fix that? I tried to but wasn't sure how to prevent it on iOS.
> @melloblue on what device does this behavior occur?

On iphone xr and xs. iOS15.2.1
