### ISSUE TITLE
Streaks are not updating Current and Maxstreak 

### ISSUE THREAD

**Issue by Toxiclikith** [MikhaD/wordle#24]

**Comment by MikhaD** [comment]
On which game mode? This could happen if you were playing the daily late at night over the transition from one day to the other, or if you were playing hourly over the the hour transition you streak would be considered broken.

**Comment by Toxiclikith** [comment]
> On which game mode? This could happen if you were playing the daily late at night over the transition from one day to the other, or if you were playing hourly over the the hour transition you streak would be considered broken.

It's daily mode after playing 3 days still current streak is 1 and Maxstreak is also 1

**Comment by Toxiclikith** [comment]
> On which game mode? This could happen if you were playing the daily late at night over the transition from one day to the other, or if you were playing hourly over the the hour transition you streak would be considered broken.

![IMG_20220222_010145.jpg](https://user-images.githubusercontent.com/75122082/155017591-5e52d7fd-74e2-4457-bc44-6a262f016528.jpg)

**Comment by MikhaD** [comment]
Alright, thank you. I'll look into it. Good to know it isn't because of the update I pushed an hour ago.

**Comment by Toxiclikith** [comment]
> Alright, thank you. I'll look into it. Good to know it isn't because of the update I pushed an hour ago.
> 

It's ok brother..

**Comment by MikhaD** [comment]
At least once your device updates to 1.1.2 the timer won't overflow anymore

**Comment by Toxiclikith** [comment]
> At least once your device updates to 1.1.2 the timer won't overflow anymore

![Screenshot_2022-02-22-01-31-28-42_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/75122082/155019453-7341480c-4d7f-46a1-b9b9-a5012af89225.jpg)

It's updated brother to v1.1.2

**Comment by rbrignall** [comment]
Hi,
I found this bug a few days back. In your version, it's line 104 of Game.svelte, which should be:
`modeData.modes[$mode].seed - stats.lastGame > modeData.modes[$mode].unit`

That is, replace `>=` with `>` (because when the difference is exactly 1 day, that should add to the current streak).

**Comment by Toxiclikith** [comment]
> Hi,
> I found this bug a few days back. In your version, it's line 104 of Game.svelte, which should be:
> `modeData.modes[$mode].seed - stats.lastGame > modeData.modes[$mode].unit`
> 
> That is, replace `>=` with `>` (because when the difference is exactly 1 day, that should add to the current streak).

I think it's 99 line which u have said

**Comment by lukeswitz** [comment]
> I have changed that line checked no changes

did you empty your browser data & cache? Seems to fix it here.

**Comment by MikhaD** [comment]
Thanks for identifying the source of the issue @rbrignall, it is now fixed. I'm surprised this wasn't reported sooner.
