### ISSUE TITLE
In game way to play historical game

### ISSUE THREAD

**Issue by MikhaD** [MikhaD/wordle#30]
**Description**
A modal that lets you either paste in the link to a historical game or input the mode and game number of a historical game you want to play.

**Reasoning**
While it is already possible to play historical games by following a link, this is inconvenient for people who have the PWA installed, as the link will take them to the browser.
There is also no in game way to find a historical game other than modifying the url.

**Implementation**
Make the PWA the [link handler](https://web.dev/pwa-url-handler/) for `mikhad.github.io/wordle`.
Add a button somewhere that pops up a new modal as described in the description.
The icon can look something like this:
![Historical game](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimage.shutterstock.com%2Fimage-vector%2Fsimple-thin-line-history-icon-260nw-1327249061.jpg&f=1&nofb=1)

**Comment by lukeswitz** [comment]
Following a prior games link with any daily game data in recipient browser shows your board as it was left. I’ve never seen the daily links work, people send them to me and it just opens the daily word. I’d just change the names of the storage the shared game looks for and reset the board.

**Comment by JasonLovesDoggo** [comment]
could having the website just set its location via window.location work? or would that bring you to the browser

**Comment by MikhaD** [comment]
I want an in game way to enter links to historical games so that people who use the Progressive Web App have access.

**Comment by JasonLovesDoggo** [comment]
If you would like, I could make that for you. I just don't know where to have the icon to open the model.

**Comment by MikhaD** [comment]
Added in version 4.0
