### ISSUE TITLE
Timer off by X hours

### ISSUE THREAD

**Issue by lukeswitz** [MikhaD/wordle#31]
Timer isn’t in sync with game.

Current:
Local time: 02:06:18 AM
Time until next wordle: 14:53:42

Expected: 
Should read : 21:53:42

**Comment by MikhaD** [comment]
Is it just the timer or is the actual game resetting at the wrong time for the given time zone?

**Comment by lukeswitz** [comment]
It resets the word too. Bummer.

**Comment by lukeswitz** [comment]
Cool
