### ISSUE TITLE
Make a way to have to have a valid guesses and a words page

### ISSUE THREAD

**Issue by BrendanDenzel** [MikhaD/wordle#34]
**Description**
A way to have a valid gusses and a words page instead of just having one

**Reasoning**
Im trying to make something and i need to keep the valid words but dont want them to be the secret word

**Comment by MikhaD** [comment]
While an interesting idea this is not something I intend to implement. Presenting the user with an actual list of valid words instead of a number, excluding the answer will just tell them what words it isn't.
