### ISSUE TITLE
Still dont see the refresh button

### ISSUE THREAD

**Issue by Jasoon967** [MikhaD/wordle#37]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser Version [e.g. 22]
 - Game Version [e.g. 1.2.0]

**Smartphone (please complete the following information):**
 - Browser Version [e.g. 22]

**Additional context**

**Comment by MikhaD** [comment]
Bug #36 has not been fixed yet. If you would like to create another bug report please fill in the template.
