### ISSUE TITLE
i tried everything and it only worked once

### ISSUE THREAD

**Issue by Jasoon967** [MikhaD/wordle#38]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser Version [e.g. 22]
 - Game Version [e.g. 1.2.0]

**Smartphone (please complete the following information):**
 - Browser Version [e.g. 22]

**Additional context**

**Comment by MikhaD** [comment]
Bug #36  has not been fixed yet. If you would like to create another bug report please fill in the template.

**Comment by Jasoon967** [comment]
can you tell me when the bug is fixed

________________________________

**Comment by Jasoon967** [comment]
thankyou so much i love this game and i play it litterally every day thank you for making this game
________________________________

**Comment by MikhaD** [comment]
You're welcome, Its great to hear that you enjoy it. Thank you for contributing to making it better. I would appreciate if you could leave a star on the repository as a sign of appreciation :)
