### ISSUE TITLE
Statistics Color Bug

### ISSUE THREAD

**Issue by DriesC-1850394** [MikhaD/wordle#39]
**Describe the bug**
Played for the first time and did not guess the word, but in the sixth row ([6] 0), the zero got a green color. this is rather confusing, since I did not find the word.

**To Reproduce**
1. Play the game for the first time
2. Do not guess the word
3. Look at the sixth row in the statistics screen

**Expected behavior**
A black (or red) color instead of a green one.

**Screenshots**
![image](https://user-images.githubusercontent.com/61016443/162979080-573f3800-f1ff-4aac-8246-493f359a155c.png)

**Comment by MikhaD** [comment]
Thank you for reporting this, I have now fixed it with version 1.3.1.
