### ISSUE TITLE
Control the words that appear every day

### ISSUE THREAD

**Issue by guiloviu** [MikhaD/wordle#42]
**Description**
I have seen that the program launches in the daily mode a random word regardless of the order but, would there be any option to have internally controlled the order with which the words would come out?

**Reasoning**
I would like to create a Wordle but that in certain days I have the control that a concrete word associated to an event celebrated that day will come out.

Thanks for everything!

**Comment by JasonLovesDoggo** [comment]
I don't think he would do this but you can just use the JavaScript date function and specify a date then check If today is that day and if so just change the word variable

**Comment by MikhaD** [comment]
One of the first things I changed when recreating the original wordle was the way words were selected. The original increments through a list of words, making it extremely easy to see what the next word is going to be (not to mention that the current answer is stored in localstorage). My goal was to create a system that still gave everyone the same word, but was much harder to predict, without some basic coding knowledge.
Not only will hard coding specific words for specific days go against that idea, but any change to how words are selected will break historical games.
Jason is correct, if you want the functionality you described, the easiest way to achieve it would be to fork the project and add some conditions inside `App.svelte` where the word is selected to overwrite a given day's word if it is a specific date.
If you intend to fork the project, please read the note on forking at the bottom of the README. Good luck.
