### ISSUE TITLE
Remove Google 

### ISSUE THREAD

**Issue by lukeswitz** [MikhaD/wordle#46]
Remove your Analytics API from this project, don’t add a “message to forkers”. This it GitHub not some random repo host.  

SEO and open source are oil and water. 

You didn’t do anything here in an original context, and “your” project is on the chopping block for NYT. 

Build something original, then talk about copyright & licensing.

**Comment by MikhaD** [comment]
I am not upset by it, nor did I expect anyone else to be. This is the first project of mine to gain minor popularity and it would seem a missed opportunity not to use it to learn as much as I can.
Should the NYT wish to take it down that would certainly be an interesting end.
Could you possibly elaborate on why you find this so aggravating?

**Comment by lukeswitz** [comment]
Tracking is invasive.

**Comment by MikhaD** [comment]
I agree it was foolish to include a request to remove my scripts when forking, as it shifts the burden to them. For now I will put wrap the analytics code in a check to make sure the document location origin is https://mikhad.github.io/, while I read more about the legality. If you have any good resources I'd appreciate if you could share them.

**Comment by lukeswitz** [comment]
Just because it's not illegal, doesn't mean it's right. Using analytics in #FoSS projects without user consent is a #privacy violation. Let's prioritize user rights and give them the ability to opt-out of data collection #opensource #privacymatters
