### ISSUE TITLE
Doesn't work on ipad 15.5

### ISSUE THREAD

**Issue by mrg9999** [MikhaD/wordle#48]
Any browser screen corrupts on entry. Game can be played but everything is on one line.
Checked in chrome, safari, duckduckgo

Worked on previous version. Works on 12.5

**Comment by MikhaD** [comment]
Could you post a screenshot and tell me the version of the game you're using?

**Comment by mrg9999** [comment]
![wordle_clone-01](https://user-images.githubusercontent.com/7822877/170842905-01b6c8d0-897e-4e3c-b5c9-f2e187f5a41b.jpg)
![wordle_clone-02](https://user-images.githubusercontent.com/7822877/170842906-8a752891-5c1d-41b4-aca7-1b983008c1a8.jpg)

**Comment by MikhaD** [comment]
consolidated into issue #61
