### ISSUE TITLE
Board keeps condensing

### ISSUE THREAD

**Issue by Cmoo-8675** [MikhaD/wordle#55]
**Describe the bug**
The Wordle board keeps condensing to be very short and super wide.

**Desktop (please complete the following information):**
 - OS: [iPad OS]
 - Browser [Safari]
 - Browser Version [???]
 - Game Version [1.3.2]

**Smartphone (please complete the following information):**
 - Device: [iPad 7th Gen]
 - OS: [15.6.1]
 - Browser [Safari]
 - Browser Version [???]

**Comment by MikhaD** [comment]
I think this is a known bug with apple devices and the `aspect-ratio` css property, but I'd need a screenshot to be sure.

**Comment by MikhaD** [comment]
Does it look like the screenshots provided in #49 or #48 ?

**Comment by MikhaD** [comment]
consolidated into issue #61
