### ISSUE TITLE
Tip text glitch

### ISSUE THREAD

**Issue by branwall** [MikhaD/wordle#6]
When moving from tip 7/9 to 8/9, some artifacts of text from 7/9 are still visible in the tip window. 
![B805A185-BEC7-4DB8-9AB5-B3AD0E4FAE32](https://user-images.githubusercontent.com/6343252/150694319-e7ea40e2-0ee0-4437-9679-84f4c468a520.jpeg)

**Comment by MikhaD** [comment]
I have been unable to recreate this issue, what device and browser are you using?

**Comment by branwall** [comment]
iPad OS / Safari.  Oddly, doesn't have this error when going back from 9/9 to 8/9.

**Comment by branwall** [comment]
https://user-images.githubusercontent.com/6343252/150696355-d0a52d88-326d-4f55-9e79-4882b364a199.MOV

**Comment by MikhaD** [comment]
This is not the only issue I've had reported from iPad Safari, I just rolled out a fix so that iOS safari can access the custom context menu. Unfortunately I don't know how to fix this. I might try shuffling up the order of the tips and see if that does anything.

**Comment by MikhaD** [comment]
@branwall I committed a change that hopefully fixes this, let me know if it is still happening and I will reopen this issue.
