### ISSUE TITLE
DOESNT GO ON AND ON

### ISSUE THREAD

**Issue by elbellepoopykittie** [MikhaD/wordle#60]
IT SAYS WORDLE PLUS BUT IT STOPS AFTER 4 WORDS. WHAT A RIP OFF!!!! TAKE DOWN THIS GAME! TAKE DOWN THIS GAME! TAKE DOWN THIS GAME! TAKE DOWN THIS GAME!  TAKE DOWN THIS GAME!  TAKE DOWN THIS GAME!  TAKE DOWN THIS GAME!  TAKE DOWN THIS GAME!  TAKE DOWN THIS GAME!  TAKE DOWN THIS TAKE DOWN THIS GAME!  TAKE DOWN THIS GAME!  TAKE DOWN THIS GAME!  TAKE DOWN THIS GAME!  TAKE DOWN THIS GAME!  TAKE DOWN THIS GAME!  TAKE DOWN THIS GAME!  TAKE DOWN THIS GAME!  TAKE DOWN THIS GAME!  TAKE DOWN THIS GAME!  TAKE DOWN THIS GAME!  TAKE DOWN THIS GAME!  GAME!  TAKE DOWN THIS GAME!  TAKE DOWN THIS GAME! FOR THE COMMUNITY!!!!!!!!!

**Comment by elbellepoopykittie** [comment]
YASSSSSSS

**Comment by elbellepoopykittie** [comment]
BURN IT DOWNNNNNNNNNNN

**Comment by elbellepoopykittie** [comment]
SCREWWWWW THISSSSS WHATTTTT A RIPPP OFFFFF!!!!!!

BROOOOOOOOO

**Comment by MikhaD** [comment]
If you want me to take you seriously please provide the steps required to recreate your issue.

**Comment by Zibri** [comment]
@elbellepoopykittie you didn't take your red pills today, didn't you?
