### ISSUE TITLE
infinite does not work

### ISSUE THREAD

**Issue by whizgames** [MikhaD/wordle#67]
**infinite mode does not do anything**
It's not really a bug just a coding problem

**To Reproduce**
1. Go to my website '...'
2. Click on this link! https://whizgames.github.io/'....'
3. Scroll down to all the games'....'
4. See all the games!!!!

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser Version [e.g. 22]
 - Game Version [e.g. 1.2.0]

**Smartphone (please complete the following information):**
 - Browser Version [e.g. 22]

**Additional context**

**Comment by MikhaD** [comment]
As far as I am aware both hourly and infinite modes work on https://mikhad.github.io/wordle. If there is an issue on your fork it is likely due to changes you've made. If you can narrow down the issue to a specific problem in my codebase I'd be happy to fix it.
