### ISSUE TITLE
Help for custom dictionary in fork

### ISSUE THREAD

**Issue by eskyo** [MikhaD/wordle#72]
Hi, 
I'm a teacher with basic programming skills trying to get this working with a custom set of words. (New to github too).
I tried to make a fork and edit "words_5.ts", then publish pages-gh but it doesn't seem to get the new words.

Should be pretty straightforward, what am doing wrong? 

Thank you!

**Comment by eskyo** [comment]
Resolved, needed to compile in vscode

**Comment by MikhaD** [comment]
Glad you got it sorted, let me know if there is anything I can do to help.
