### ISSUE TITLE
apsect-ratio causing issues on old devices

### ISSUE THREAD

**Issue by MikhaD** [MikhaD/wordle#8]
The aspect ratio property is causing issues on old devices where it is not supported, see [img](https://ibb.co/PmGV6nx)

**Comment by JakeWasChosen** [comment]
It also happens on newer devices with odd aspect ratios.

Or if the page was zoomed out a lot.

**Comment by MikhaD** [comment]
What do you mean with odd aspect ratio? This issue is here because of the limited support for the `aspect-ratio` CSS property which is not supported on older versions of certain browsers.

Could you give an example of what you mean?

**Comment by JakeWasChosen** [comment]
problem causes include:
Smaller resolutions
Extreme resolutions e.g. a much higher width then height and vice versa
And it becomes worse and worse the smaller of the resolution 

( Tested on Chrome version 98.0.4758.102)

**Comment by JakeWasChosen** [comment]
Hey, sorry for the late response I was unavailable at the time

Images:
https://i.imgur.com/SGcp5YD.png
https://i.imgur.com/hULvvqW.png
https://i.imgur.com/TiJQidN.png

Not really that big of a problem as I don't know many devices that have aspect ratios like what's needed to replicate this bug
Also, I noticed that the answer boxes only scale when vertical changes happen not horizontal which leads to clipping

**Comment by MikhaD** [comment]
Potentially fixable with `margin-top` aspect ratio hack and @supports(aspect-ratio: 1)

**Comment by JasonLovesDoggo** [comment]
Also are you working on a fix for #48

**Comment by lukeswitz** [comment]
I’ve got a dozen in the lab. I’ll test for you guys, least I can do. Simple fix.

**Comment by JasonLovesDoggo** [comment]
That looks fine on my end

**Comment by lukeswitz** [comment]
> That looks fine on my end

Did you set it to iPad Pro and then enter a word? I can replicate the bug every time.

**Comment by JasonLovesDoggo** [comment]
> Edit: here’s a front end resolution tool that shows the problem using the iPad Pro:
> 
> https://screenfly.org/#u=https%3A//mikhad.github.io/wordle/%23daily&w=1366&h=1024&a=22
> 
> Enter a word, problem is replicable. Very easy to debug from there. Cheers. 

![Screenshot_20220612-091747.png](https://user-images.githubusercontent.com/66544866/173235153-80c12778-3aec-4155-8e66-3dbbdb2e2f6a.png) It works perfectly fine for me

**Comment by lukeswitz** [comment]
![1196C2C7-F606-4AB6-BB8D-6F79942B882D](https://user-images.githubusercontent.com/10099969/173235238-ce12d940-9e9f-483c-b5dd-9b6e80d38496.jpeg)

That’s nice. What device and AOS?

**Comment by MikhaD** [comment]
consolidated into issue #61
