### ISSUE TITLE
Double letter handling does not match OG wordle

### ISSUE THREAD

**Issue by cwinget** [MikhaD/wordle#9]
![Screenshot_20220124-182900_Samsung Internet](https://user-images.githubusercontent.com/7170724/150893845-d32514e6-c808-4312-a573-f3245d26cdb9.jpg)

See screenshot. In OG Wordle, the first E would be yellow, and the last E would be grey. Both Es highlighted yellow in the guess suggests that there are two Es in the word.
 
If the word was KEEPS, and I guess EAGLE, the both Es highlighted yellow would be correct.

**Comment by cwinget** [comment]
I just noticed you had a commit from yesterday that looks like it's intended to fix this. I'm not sure if the fix didn't work, or if I happen to have seen an old version?

**Comment by MikhaD** [comment]
Does the version you have say 1.1.1 in the bottom right corner? If not this has been fixed.

**Comment by cwinget** [comment]
![Screenshot_20220125-155353_Samsung Internet](https://user-images.githubusercontent.com/7170724/151073418-2f886139-89be-4aad-9e85-e5edb0c6be47.jpg)

It appears to be fixed if the letters are apart, but is still a problem if they're sequential.

**Comment by cwinget** [comment]
I am currently on 1.1.1, yes. I'm not sure what I was on yesterday, but apparently it was different.

**Comment by birchmeierlogan** [comment]
![image](https://user-images.githubusercontent.com/84031054/151292533-7c957175-3a14-4676-8ae4-c8488894430f.png)
![image](https://user-images.githubusercontent.com/84031054/151292557-ca140fff-a8ee-421b-aed0-d91e469b09c6.png)

Not sure if this has been resolved but would like to add more data from version 1.1.1

**Comment by MikhaD** [comment]
Not yet resolved, working on it now.

**Comment by birchmeierlogan** [comment]
![image](https://user-images.githubusercontent.com/84031054/151677921-bd2f5ec2-9698-4b88-b55e-a09485704b78.png)
![image](https://user-images.githubusercontent.com/84031054/151677922-98df9af1-4a31-431f-a1e6-237df606d29a.png)

To me it seems like if a guess contains a correct letter in the wrong place, all of that letter gets marked yellow.
I don't think this matches original wordle but it's not necessarily wrong (since the letter is not in either position)

**Comment by rbrignall** [comment]
Hi all,
I also believe the code as written is not currently correct, and I have fixed it in my forked version (now very different from yours, so I can't submit a pull request right now). The following version of getState does the right thing, I believe:

```
export function getState(word: string, guess: string): LetterState[] {
	const charArr = word.split("");
	const result = Array<LetterState>(5).fill("⬛");
	for (let i = 0; i < word.length; ++i) {
		if (charArr[i] === guess.charAt(i)) {
			result[i] = "🟩";
			charArr[i] = "$";
		}
	}
	for (let i = 0; i < word.length; ++i) {
		if (charArr.includes(guess.charAt(i)) && result[i] !== "🟩") {
			result[i] = "🟨";
			charArr[charArr.indexOf(guess.charAt(i))] = "$";
		}
	}
    
	return result; //result.map((e, i) => charArr.includes(guess[i]) && e !== "🟩" ? "🟨" : e);
}
```
